### PR TITLE
Homogenise `.buildbot.sh` with yklua.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by vext01** [comment]
Please squash.

**Comment by ltratt** [comment]
Squashed.

**Comment by ltratt** [comment]
It's our nondeterministic (gcc?) error again...

**Comment by vext01** [comment]
Looks like it.

I have a diff for that. Will raise a pr on Monday after testing.

Bors r+

**Pull request merged**
