### PR TITLE
Run CI inside docker.

### PR DESCRIPTION
**Pull request by vext01**
See commits.

Depends on https://github.com/softdevteam/buildbot_config/pull/69

### CODE REVIEW

**Comment by ltratt** [comment]
Please force push an update (including squashing if necessary) that updates the bors file.

**Comment by vext01** [comment]
No squashing needed here.

**Comment by vext01** [comment]
This'll need squashing.

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
This is good for squashing then.

Then I'll go and fix all the other PRs.

(sorry about this, I raised too many PRs at once and made a mess)

**Comment by vext01** [comment]
OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Pull request merged**
