### PR TITLE
Transition repo to GHMQs.

### PR DESCRIPTION
**Pull request by vext01**
I think this should work

### CODE REVIEW

**Comment by vext01** [comment]
Hrm, I uninstalled bors, so I'm not sure why we still have that...

**Comment by ltratt** [comment]
@vext01 Note this repo doesn't have a `.github` directory etc. I guess you'll need to add that (or similar) to this PR.

**Comment by vext01** [comment]
This PR adds it :)

Try now, I hadn't confirmed the new branch protection rules.

**Comment by vext01** [comment]
I see the CI job running :)

**Comment by vext01** [comment]
Huh. I wasn't expecting that to work. I thought we'd need the changes from https://github.com/ykjit/ykcbf/pull/21 so that CI worked...

**Pull request merged**
