### PR TITLE
Add a test suite.

### PR DESCRIPTION
**Pull request by ltratt**
This also requires us to be clear about the copyright, as some of the test files are copyrightable.

### CODE REVIEW

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
For reasons I don't understand, once in a while hanoi.bf takes noticeably longer to run than normal. In retrospect it's not a very useful test, because all we can do is check that it completes without an error.

bors try-

**Comment by ltratt** [comment]
bors ping

**Comment by ltratt** [comment]
bors try-

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
Ok, something else is going wrong in here -- possibly in lang_tester.

**Comment by ltratt** [comment]
I think this is ready for squashing, though we shouldn't attempt merging until https://github.com/softdevteam/lang_tester/pull/87 is merged and a new lang_tester released.

**Comment by vext01** [comment]
Please squash

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
